planner_frequency: 1.0
planner_patience: 15.0

controller_frequency: 5
controller_patience: 15.0

# Our carlike robot is not able to rotate in place
clearing_rotation_allowed: false

GlobalPlanner:
  use_dijkstra: true
  use_grid_path: false
  allow_unknown: false

